# Generated by Django 4.2.7 on 2024-03-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('is_phishing', models.BooleanField()),
                ('username', models.CharField(max_length=150)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
